Search API
JJCSA/backend pull request #102
Opened 2022-03-06 23:16 UTC by sanketshah1997

Before Merging we need to create a view in Stage Database as below. Did not added the view definition in liquibase yet as It might conflict with email changes etc.

DO
$do$
BEGIN
	IF NOT EXISTS(
		SELECT COUNT(*) FROM INFORMATION_SCHEMA.VIEWS WHERE  TABLE_NAME = 'jjc_search_view'
	) THEN 
  	CREATE OR REPLACE VIEW JJC_SEARCH_VIEW AS 
		SELECT
		   u.ID AS USER_ID,
		   CONCAT(u.FIRST_NAME ,' ', u.MIDDLE_NAME,' ', u.LAST_NAME) as FULL_NAME, 
		   u.STATE AS LIVING_STATE, 
		   u.CITY AS LIVING_CITY, 
		   e.SPECIALIZATION AS WORK_SPECIALIZATION,
		   e.UNIVERSITY_NAME AS UNIVERSITY,
		   w.ROLE AS WORK_ROLE 
		FROM USER_ACCOUNT u
			LEFT OUTER JOIN 
		 EDUCATION e on e.USER_ID = u.ID
			LEFT OUTER JOIN WORK_EX w on w.USER_ID = u.ID;
	END IF;
END
$do$

2022-04-02 19:51 UTC, shah-tejas requested changes
Creating DB views would add another layer of business logic we need to maintain. If we are only trying to transpose db entity to a different dto which has different fields, we can do it this way without creating a view:

1. Create a new dto. Ex: SearchUser.java which contains all the required fields in the way we need.
2. Add a new method to `UserMapper.java` which provides the mapping from `User.java` to `SearchUser.java`
3. Create a new method in `UserService.java` which fetches the data from UserRepository and calls the mapper method and return `List<SearchUser>`.

2022-04-02 19:51 UTC, shah-tejas commented on pom.xml
> +		<log4j2.version>2.17.0</log4j2.version>
latest version for this is `2.17.1` with the vuln fixed

2022-04-30 04:38 UTC, Nishit-Gopani approved these changes

2022-05-06 01:20 UTC, shah-tejas approved these changes

2022-05-07 07:13 UTC, merged