Added endpoint getUsersList for UserController.
JJCSA/backend pull request #39
Opened 2021-02-01 03:03 UTC by mehta-jainam

## getUserList API

Added Endpoint getUsersList for user

Issue#15

2021-02-07 22:47 UTC, shah-tejas requested changes

2021-02-07 22:47 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserController.java
> +    @GetMapping(path = "/getUsersList")
Let's change the url path to `users`.
Since it's a `GET` request it'll be implicit.

2021-02-07 22:47 UTC, shah-tejas commented on src/main/java/com/jjcsa/security/WebSecurityConfig.java
> +                .antMatchers("/api/users/getUsersList").hasRole(KeycloakUtil.ADMIN)
Change the url to `/api/users`

2021-02-07 22:47 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserController.java
> +        List<UserProfile> results = new ArrayList<>();
Do not need to initialize this List as it will fetch an instances from the service method

2021-02-07 22:47 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserController.java
> +        }catch (NullPointerException e) {
Add exception handling in the service method itself.

2021-02-09 22:55 UTC, dishanks9 commented on src/main/java/com/jjcsa/controller/UserController.java
> +        }catch (NullPointerException e) {
Also handle other exceptions since if we have any exception other NPE it would cause unexpected behavior. Also in the log.error, log the actual exception along with the message like log.error(message, e)

2021-02-10 05:53 UTC, mehta-jainam commented
Added Latest Changes!

2021-02-10 20:40 UTC, shah-tejas requested changes

2021-02-10 20:40 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserController.java
> +            UserProfileService ups = new UserProfileService();
Use the Autowired profile service already defined in this class, instead of creating a new one

https://github.com/JJCSA/backend/blob/69a534427783e4401aea8a690ce38a9d7c73b49d/src/main/java/com/jjcsa/controller/UserController.java#L42

2021-02-10 20:40 UTC, shah-tejas commented on src/main/java/com/jjcsa/service/UserProfileService.java
> +    public List<UserProfile> getall()
Add exception handling here and you can also make this method name more descriptive, calling it `getAllUsers()` or something

2021-02-11 06:01 UTC, mehta-jainam commented
Updated latest changes, Please review.

2021-02-11 15:11 UTC, shah-tejas approved these changes

2021-02-11 21:02 UTC, dishanks9 approved these changes

2021-02-11 21:41 UTC, merged