Add manageruser APIs
JJCSA/backend pull request #51
Opened 2021-05-01 16:46 UTC by dishanks9

## Description

Add 2 APIs
1. updateUserDetails - For updating user profile and approving user by admin
2. updateUserRole - Making/Removing user as admin

## Issue

Fixes #<i16>

## Checklist
- [Yes ] I have commented my code in hard-to-understand areas
- [N/A ] I have created relevant Unit Tests for the feature I implemented
- [Yes ] I have pulled and merged the latest code and resolved all merge conflicts
- [ Yes] I have added someone to review this PR, and informed the team on Slack

2021-05-01 17:24 UTC, shah-tejas commented on src/main/java/com/jjcsa/security/WebSecurityConfig.java
> +                .antMatchers("/api/users/updateUserDetails").authenticated()
I think authentication is enforced on all APIs, might not need to specify here.

2021-05-01 17:27 UTC, shah-tejas commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +        System.out.println(addNewUser);
Lets `log` instead of SOP :)

2021-05-01 17:31 UTC, shah-tejas commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +    public static void updateUserRole(@NonNull String role,
Let's make this a private method and then public methods that call this method like:
- `updateUserRoleToAdmin(...)`
- `updateUserRoleToSuperAdmin(...)`

This will prevent any unknown roles being added from any APIs

2021-05-01 17:33 UTC, shah-tejas commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +                               @NonNull String serverUrl) {
`serverUrl` would be fixed right? Why should it be a method parameter?
Can simply fetch it from `application.properties` or something and then define it as a final String?

2021-05-01 17:36 UTC, shah-tejas commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +                               @NonNull String serverUrl) {
Basically move https://github.com/JJCSA/backend/blob/342d9880a31bbd582529d33f6a6f84e864290cc5/src/main/java/com/jjcsa/controller/UserController.java#L39

this from `UserController `to `KeycloakUtil`?

2021-05-01 17:39 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +@RequestMapping(path="/api/users", produces = "application/json")
So this is good. Let's have APIs like this:
- GET `/api/user/profile`
- PUT `/api/user/profile`

2021-05-01 17:40 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +@RequestMapping(path="/api/users", produces = "application/json")
So change this to 
```
@RequestMapping(path="/api/user/profile", produces = "application/json")
```

2021-05-01 17:41 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +    @GetMapping(path = "/profile")
No need to give path here, since defined on class level

2021-05-01 17:41 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +    @PutMapping(path = "/updateUserDetails")
+1 remove path

2021-05-01 17:47 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +        if(token.isActive()){
Spring Security validates tokens, no need to check this

2021-05-01 17:51 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +            if(!UserUtil.isUserApproved(actionPerfomerDetails)){
No need for this. User should already be approved if Admin

2021-05-01 17:52 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +            @RequestParam("actionPerformerEmail") @NonNull final String actionPerformerEmail,
No need for this. Email can be fetched from the auth token

2021-05-01 17:55 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +    public ResponseEntity<String> updateUserDetails(
So I am confused about this API. It is for Admin to update another user's profile right?
If user wants to update their profile it should be a different endpoint.
Maybe this might be a good time to add a `AdminController` that has all Admin related APIs like:
- GET `/admin/users`
- PUT `/admin/users/{id}/profile`

OR something to differentiate Admin apis and user apis

2021-05-01 17:57 UTC, shah-tejas requested changes
So, I think we need to differentiate Admin related APIs and User related APIs.
User updating their own stuff should be a different endpoint, and admin updating user should be different.

2021-05-05 06:36 UTC, Nishit-Gopani commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +    public ResponseEntity<String> updateUserDetails(
I agree, lets separate out right now. It will be good to have admin controller which will handle all admin related API.

2021-05-05 06:40 UTC, Nishit-Gopani commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +            if(!UserUtil.isUserApproved(actionPerfomerDetails)){
Correct, This is how it will work 
1. First SuperAdmin will approve user.
2. SuperAdmin can assign approved user as an Admin ( In order to make user admin, user should be approved)
3. Admin can approve/decline user based on details submitted but, admin cannot make any other person an Admin.

2021-05-08 16:42 UTC, dishanks9 commented on src/main/java/com/jjcsa/security/WebSecurityConfig.java
> +                .antMatchers("/api/users/updateUserDetails").authenticated()
I'll remove this and add admin related APIs here

2021-05-08 16:43 UTC, dishanks9 commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +        System.out.println(addNewUser);
Good catch. Mistakenly left this here.

2021-05-08 16:44 UTC, dishanks9 commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +                               @NonNull String serverUrl) {
Same as above

2021-05-08 16:46 UTC, dishanks9 commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +@RequestMapping(path="/api/users", produces = "application/json")
What if there are more APIs related to userProfile, can do something like 
GET /api/user/profile - method level
PUT /api/user/profile - method level

since that would make it more flexible to add more APIs

2021-05-08 16:47 UTC, dishanks9 commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +    @PutMapping(path = "/updateUserDetails")
Same as above

2021-05-08 16:47 UTC, dishanks9 commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +        if(token.isActive()){
Okay will remove this

2021-05-08 16:48 UTC, dishanks9 commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +            @RequestParam("actionPerformerEmail") @NonNull final String actionPerformerEmail,
Would use that in Admin APIs

2021-05-08 16:49 UTC, dishanks9 commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +    public ResponseEntity<String> updateUserDetails(
Sure

2021-05-12 01:53 UTC, shah-tejas commented on src/main/java/com/jjcsa/controller/UserProfileController.java
> +@RequestMapping(path="/api/users", produces = "application/json")
Well if the APIs are not related to userProfile, it should not go in this controller.
This is fine, but you can also do something like this:
```
@RequestMapping(path="/api/user/profile", produces = "application/json")
public class ProfileController {

  @GetMapping
  public UserProfile getProfile() {
     ...
  }

  @PutMapping
  public UserProfile updateProfile() {
     ...
  }

}
```

This is not super important though...

2021-08-29 23:43 UTC, closed without merging