[Delete User_44] Delete User functionality added to jjcsa
JJCSA/backend pull request #52
Opened 2021-05-04 02:07 UTC by sanketshah1997

## Description

Added Delete User Functionality for JJCSA.

## Issue

Fixes #44 

## Checklist
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have created relevant Unit Tests for the feature I implemented
- [ ] I have pulled and merged the latest code and resolved all merge conflicts
- [ ] I have added someone to review this PR, and informed the team on Slack

2021-05-05 00:10 UTC, shah-tejas approved these changes
Minor changes, looks good otherwise!

2021-05-05 00:10 UTC, shah-tejas commented on src/main/java/com/jjcsa/exception/ExceptionInterceptor.java
> +        return new ResponseEntity(exceptionResponse, HttpStatus.INTERNAL_SERVER_ERROR);
Shouldn't this be a 4xx error?
Internal Server Error is a 5xx error

2021-05-05 00:10 UTC, shah-tejas commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +    @Value("${keycloak.auth-server-url}")
```
@Value("${keycloak.auth-server-url}")
public static String keycloakServerUrl;
```
Just this should work too right?

2021-05-05 00:10 UTC, shah-tejas commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +    @Value("${keycloak.auth-server-url}")
actually this variable should be `final` no need to be `static`

2021-05-05 00:10 UTC, shah-tejas commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +    @Value("${keycloak.auth-server-url}")
If it needs to be exposed to other classes, making it a `@Bean` would be a better idea
That way, the app won't come up if this property is not defined.

2021-05-05 00:10 UTC, shah-tejas commented on src/test/java/com/jjcsa/service/UserServiceTest.java
> +    private String keycloakServerUrl;
This should be mocked I think.
Unit test wont be able to reach to Keycloak (it shouldn't)
Good use case for [Mockito](https://www.baeldung.com/injecting-mocks-in-spring)

2021-05-05 00:10 UTC, shah-tejas commented on src/test/resources/application-test.yml
> +# Endpoints
+1 to use yml for properties!

2021-05-05 01:36 UTC, sanketshah1997 commented on src/test/java/com/jjcsa/service/UserServiceTest.java
> +    private String keycloakServerUrl;
yes, agree. was planning to include Junit test for isAdmin functionality using rest template.

2021-05-05 01:36 UTC, sanketshah1997 commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +    @Value("${keycloak.auth-server-url}")
Spring does not allow the injection of public static fields. so direct value annotation on-field won't work here. Agree field should be final. Tried using the final at first but it requires initialization so It should be constructor injection. was following the same design pattern in the code. hence used the static field.. btw will be adding default values for the fields in the next commit...

2021-05-05 01:36 UTC, sanketshah1997 commented on src/main/java/com/jjcsa/exception/ExceptionInterceptor.java
> +        return new ResponseEntity(exceptionResponse, HttpStatus.INTERNAL_SERVER_ERROR);
Not sure what is appropriate for this.

2021-05-05 01:36 UTC, sanketshah1997 commented on src/main/java/com/jjcsa/controller/UserController.java
> +        if(keycloakUtil.isAdmin(account)) {
agree.

2021-05-05 03:27 UTC, shah-tejas commented on src/main/java/com/jjcsa/exception/ExceptionInterceptor.java
> +        return new ResponseEntity(exceptionResponse, HttpStatus.INTERNAL_SERVER_ERROR);
Well technically if we do with Spring's OOTB features the request would never reach our code. Spring security will look for role of user and if we do something like `@Secured("ROLE_ADMIN")`, Spring will handle that error.

2021-05-05 06:27 UTC, Nishit-Gopani commented on src/main/java/com/jjcsa/controller/UserController.java
> +    @PostMapping(path = "delete/{userId}")
We can keep this method for now. In case, after approval if admin wants to delete the user this method can be used moving forward.

2021-05-05 06:30 UTC, Nishit-Gopani commented on src/main/java/com/jjcsa/controller/UserController.java
> +    public String deleteUser(KeycloakAuthenticationToken authenticationToken, @PathVariable String userId) throws UserRoleException {
Also, we can ask frontend team to include user Id. I think we should use user Id instead of using email.

2021-05-09 03:39 UTC, dishanks9 requested changes

2021-05-09 03:39 UTC, dishanks9 commented on src/main/java/com/jjcsa/controller/AdminController.java
> +@Secured("ROLE_ADMIN")
Why is this required if its already done using antmatchers?

2021-05-09 03:39 UTC, dishanks9 commented on src/main/java/com/jjcsa/controller/AdminController.java
> +    AdminController(UserService userService){
Use @RequiredArgsConstructor

2021-05-09 03:39 UTC, dishanks9 commented on src/main/java/com/jjcsa/runner/KeycloakAdminConfig.java
> +    @Value("${keycloak.auth-server-url:http://localhost:8080/auth}")
why to add url if it can fetch from application.properties. It should be like @Value("${keycloak.auth-server-url}")

2021-05-09 03:39 UTC, dishanks9 commented on src/main/java/com/jjcsa/runner/KeycloakInitializerRunner.java
> +    @Value("${keycloak.auth-server-url:http://localhost:8080/auth}")
Same as above

2021-05-09 03:39 UTC, dishanks9 commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +    public boolean isAdmin(SimpleKeycloakAccount account){
I don't see this method being used anywhere. If not required then remove this

2021-05-09 11:12 UTC, sanketshah1997 commented on src/main/java/com/jjcsa/runner/KeycloakAdminConfig.java
> +    @Value("${keycloak.auth-server-url:http://localhost:8080/auth}")
It is just default value. It will definitely fetch it from application.yml file but if there is no such property exist it will get the default value.

2021-05-09 11:12 UTC, sanketshah1997 commented on src/main/java/com/jjcsa/controller/AdminController.java
> +    AdminController(UserService userService){
Btw @data will take of that but agree need to remove the constructor. Added for spring dependencies injection. Did not want to use @Autowired.

2021-05-09 11:12 UTC, sanketshah1997 commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +    public boolean isAdmin(SimpleKeycloakAccount account){
Agree. Just forgot to remove this. It was used before adding the admin controller.

2021-05-12 02:06 UTC, shah-tejas reviewed
Minor changes

2021-05-12 02:06 UTC, shah-tejas commented on src/main/java/com/jjcsa/util/KeycloakUtil.java
> +        return KeycloakBuilder.builder()
We should change this to make `Keycloak` final. Every time, this method is called it will create new `Keycloak` instance right?
This can simply be made final and/or exposed as a `@Bean` since all the variables required to build this are static.

2021-05-17 00:30 UTC, Nishit-Gopani approved these changes
Looks good :)

2021-05-17 00:34 UTC, dishanks9 approved these changes

2021-05-17 00:35 UTC, merged