Aws Parameter Store Integration and keycloak version change
JJCSA/backend pull request #65
Opened 2021-07-28 03:09 UTC by sanketshah1997

## Description

<Please include a brief description of the code changes>

## Issue

Fixes #<issue_number>

## Checklist
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have created relevant Unit Tests for the feature I implemented
- [ ] I have pulled and merged the latest code and resolved all merge conflicts
- [ ] I have added someone to review this PR, and informed the team on Slack

2021-07-28 04:27 UTC, shah-tejas requested changes
Use the paramstore dependency from: https://mvnrepository.com/artifact/io.awspring.cloud/spring-cloud-aws-parameter-store-config/2.3.1

Derive the version value from `${spring-cloud-aws-version}` which is already set to `2.3.1`.

Also, `spring-cloud-starter` can be removed if not used.

2021-07-28 04:27 UTC, shah-tejas commented on pom.xml
> +		<keycloak.version>13.0.1</keycloak.version>
To be in sync, could you also update keycloak version in [docker-compose.yml](https://github.com/JJCSA/Authentication/blob/92b6a715d14b3a14e445dcbaeefad4db5b10485b/docker-compose.yml#L17) and also have Dushyant use the same keycloak version in infra?

2021-07-28 04:27 UTC, shah-tejas commented on pom.xml
> +			<groupId>org.springframework.cloud</groupId>
So the spring cloud version that is compatible with Spring Boot 2.4.x is now maintained under a different groupId: https://awspring.io/learn/introduction/#versions

We should use the dependency coming from  `<groupId>io.awspring.cloud</groupId>` as this is the latest one which will be supported with future versions of spring boot. Also read [this](https://spring.io/blog/2021/03/17/spring-cloud-aws-2-3-is-now-available) blog for more info.

It should be done similar to `spring-cloud-aws-autoconfigure`:
https://github.com/JJCSA/backend/blob/d668f33a9577d589aef7720c0afaa566f4b67b74/pom.xml#L80

2021-07-28 04:29 UTC, shah-tejas commented
It might also be better to define the aws cloud dependencies from the pom:

```
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-aws-dependencies</artifactId>
			<version>2.3.0</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

2021-07-28 22:50 UTC, Nishit-Gopani commented on pom.xml
> +		<keycloak.version>13.0.1</keycloak.version>
I think Dushyant have updated the version in docker. We are using updated version on infra.

2021-07-31 14:45 UTC, sanketshah1997 commented on pom.xml
> +			<groupId>org.springframework.cloud</groupId>
Thanks for providing reference to the latest docs. I was referring to old docs. so this starter dependency was needed when we use org.springframework.cloud for aws parameter store.

2021-07-31 14:46 UTC, closed without merging